spring.application.name=API_MONGO
#spring.mongodb.uri=mongodb://localhost:27017/libreria_db
spring.mongodb.uri={MONGO_URI: mongodb+srv://edersalazar00_db_user:jhcpHZ9nfqmELPtF@cluster0.useu1ab.mongodb.net/?appName=Cluster0}
